# Generated by Django 4.1.7 on 2023-03-29 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SizeTranslationGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('US', models.FloatField()),
                ('UK', models.FloatField()),
                ('EU', models.FloatField()),
                ('RU', models.FloatField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INT', models.CharField(max_length=15)),
                ('US', models.CharField(max_length=15)),
                ('UK', models.CharField(max_length=15)),
                ('EU', models.CharField(max_length=15)),
                ('IT', models.CharField(max_length=15)),
                ('RU', models.CharField(max_length=15)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bucket_link', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('article', models.CharField(max_length=255)),
                ('available_flag', models.BooleanField()),
                ('last_upd', models.DateTimeField()),
                ('add_date', models.DateField()),
                ('fit', models.IntegerField()),
                ('rel_num', models.IntegerField()),
                ('brand', models.ManyToManyField(related_name='products', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.gender')),
                ('sizes', models.ManyToManyField(related_name='products', to='products.size')),
                ('tags', models.ManyToManyField(related_name='products', to='products.tag')),
            ],
        ),
    ]
